spring:
  config:
    active:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:testdb;MODE=MySQL
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080
  tomcat:
    mbeanregistry:
      enabled: true

management:
  server:
    port: 8080
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"